# remote_theme: sproogen/modern-resume-theme
# plugins:
#   - jekyll-seo-tag


# repository: SupratimManna/Resume
# version: 2

# # Personal info
# name: Supratim Manna
# title: Data Scientist | AI/ML Researcher
# email: supratimmannas7@gmail.com
# phone: +91 
# website: https://github.com/Supratimmannas7

# darkmode: false

# github_username: Supratimmannas7
# linkedin_username: supratim-manna-728315293
# kaggle_username: supratimmanna7
# youtube_username: SupratimManna

# about_profile_image: images/profile.png
# about_content: |
#   My research interests lie in LLM, GANs, and Diffusion Models for generative tasks, leveraging my strong mathematical background in probability, optimization, and numerical methods. I have worked with deep learning architectures for anomaly detection and Maritime Traffic Prediction. 


# content:
#   - title: Projects
#     layout: list
#     content:
#       - layout: left
#         border: weak
#         title: Exoplanet Detection using ML
#         link: https://github.com/Supratimmannas7/Exoplanet-Detection
#         link_text: GitHub Repository
#         additional_links:
#           - title: GitHub
#             icon: fab fa-github
#             url: https://github.com/Supratimmannas7/Exoplanet-Detection
#         quote: "Using k-NN for identifying exoplanets from light intensity data."
#         description: |
#           Developed an ML-based approach to detect exoplanets using **k-NN** on light curves, enhancing classification accuracy in astronomical research.
      
#       - layout: left
#         border: weak
#         title: CyberAICup 2024 - Network IDS
#         link: https://github.com/Supratimmannas7/CyberAICup2024
#         link_text: GitHub Repository
#         additional_links:
#           - title: GitHub
#             icon: fab fa-github
#             url: https://github.com/Supratimmannas7/CyberAICup2024
#         quote: "AI-driven Intrusion Detection using LightGBM."
#         description: |
#           Built a **Network Intrusion Detection System** (NIDS) using **LightGBM**, enhancing security with real-time monitoring.
  
#   - title: Experience
#     layout: list
#     content:
#       - layout: right
#         title: Innovate Intern - AI/ML
#         sub_title: AICTE Virtual Internship
#         caption: July 2024 - November 2024
#         quote: "Exploring AI applications through real-world projects."
#         description: |
#           Worked on **Deep Learning and NLP** projects, gaining hands-on experience in **Transformer models, GANs, and AI ethics**.
  
#   - title: Education
#     layout: list
#     content:
#       - layout: top-right
#         title: Defence Institute of Advanced Technology (DIAT-DRDO)
#         sub_title: M.Sc. Data Science (Applied Mathematics)
#         caption: 2023 - 2025
#         description: |
#           Focused on **Machine Learning, Deep Learning, and Generative AI**, with research on **AIS anomaly detection**.
  
#   - title: Skills
#     layout: text
#     content: |
#       **Programming:** Python, SQL, R  
#       **ML/DL Frameworks:** TensorFlow, PyTorch, Scikit-learn  
#       **Data Science:** Pandas, NumPy, Seaborn, Matplotlib  
#       **AI Techniques:** CNN, LSTM, GANs, Transformers, Diffusion Models  
#       **Mathematical Background:** Linear Algebra, Probability, Graph Theory  

# footer_show_references: false

# sass:
#   sass_dir: _sass
#   style: compressed

# plugins:
#  - jekyll-seo-tag

# exclude : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/"]

# plugins:
#  - jekyll-seo-tag

# exclude : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/"]




remote_theme: sproogen/modern-resume-theme
plugins:
  - jekyll-seo-tag

repository: SupratimManna/Resume
version: 2

# Personal info
name: Supratim Manna
title: Data Scientist | AI/ML Researcher
email: supratimmannas7@gmail.com
phone: +91
website: https://github.com/Supratimmannas7

darkmode: false

github_username: Supratimmannas7
linkedin_username: supratim-manna-728315293
kaggle_username: supratimmanna7
youtube_username: SupratimManna

about_profile_image: images/profile.png
about_content: |
  My research interests lie in LLM, GANs, and Diffusion Models for generative tasks, leveraging my strong mathematical background in probability, optimization, and numerical methods. I have worked with Machine learning architectures for anomaly detection. 

content:
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Defence Institute of Advanced Technology (DIAT-DRDO)
        sub_title: M.Sc. Data Science (Applied Mathematics)
        caption: 2023 - 2025
        description: |
          

      - layout: top-right
        title: Midnapore College (Autonomous)
        sub_title: B.Sc. Mathematics (Hons.)
        caption: 2020 - 2023
        description: |
          

      - layout: top-right
        title: WBCHSE, West Bengal
        sub_title: Higher Secondary
        caption: 2020
        description: |
          

      - layout: top-right
        title: WBBSE, West Bengal
        sub_title: Secondary Education
        caption: 2018
        description: |
          

  - title: Research Interests
    layout: text
    content: |
      -  My research interests lie in LLM, GANs, and Diffusion Models for generative tasks, leveraging my strong mathematical background in probability, optimization, and numerical methods. I have worked with Machine learning architectures for anomaly detection

  - title: Publications
    layout: list
    content:
      - layout: left
        title: Isolation Forest-based Anomaly Detection of Vessels using AIS Data
        sub_title: "S. Manna & Dr. B. Ramkrishna"
        caption: ICDMAI 2025 (Accepted & Presented, Jan 2025)

      # - layout: left
      #   title: Maritime Traffic Prediction using Synthetic AIS Data
      #   sub_title: "S. Manna & Dr. B. Ramkrishna"
      #   caption: Submitted to IEEE Sensors (March 2025)

  - title: Projects
    layout: list
    content:

      - layout: left
        border: weak
        title: Exoplanet Detection using ML
        link: https://github.com/Supratimmannas7/Exoplanet-Detection
        link_text: GitHub Repository
        description: |
          This project investigates the detection of exoplanets using machine learning, specifically employing the K-Nearest Neighbors (k-NN) algorithm to analyze light intensity data. Utilizing a dataset downloaded from Kaggle, which includes light curves of various celestial bodies, we focus on identifying patterns indicative of exoplanets. The k-NN model is trained on labeled data to distinguish between exoplanets and non-exoplanetary candidates based on fluctuations in light intensity. Our findings demonstrate that k-NN can effectively enhance classification accuracy, providing a promising avenue for future research in exoplanet detection and contributing to our understanding of planetary systems beyond our solar system.
      
      - layout: left
        border: weak
        title: CyberAICup 2024 - Network IDS
        link: https://github.com/Supratimmannas7/CyberAICup2024
        link_text: GitHub Repository
        description: |
          This project encompasses innovative components developed for the CyberAICup 2024 competition, focusing on advancements in network security. The Network Intrusion Detection project employs a machine learning approach to enhance cybersecurity. By using interpolation techniques on payload data, the model is trained with LightGBM to effectively identify potential network intrusions. This innovative solution aims to improve detection accuracy (98.71%) and response times in real-time network monitoring.

      - layout: left
        border: weak
        title: 3D Object Detection for Autonomous Vehicles
        link: https://github.com/Supratimmannas7/yolov8-object-tracking
        link_text: GitHub Repository
        description: |
          This project focuses on 3D object detection for autonomous vehicles, leveraging a pre-trained model sourced from GitHub.The objective is to enhance the safety and reliability of autonomous driving systems by accurately detecting and classifying objects in real-time. We utilized camera-recorded video for testing, allowing the model to analyze its surroundings and produce rectangular 2D bounding boxes around detected objects. Through comprehensive evaluation, we assess the model's performance in terms of detection accuracy and processing speed. The results demonstrate the model's effectiveness in real-world scenarios, contributing to advancements in object recognition systems and improving the overall functionality of autonomous vehicles.

      - layout: left
        border: weak
        title: Movie Recommender System TMDB
        link: https://github.com/Supratimmannas7/Movie-Recommender-System-TMDB
        link_text: GitHub Repository
        description: |
          This project presents a Movie Recommender System utilizing data from The Movie Database (TMDB) to provide personalized movie suggestions. By integrating datasets containing movie details and credits, we preprocess and extract relevant features such as genres, keywords, cast, and crew. Using a bag-of-words approach with Count Vectorization, we create a similarity matrix based on text data from these features. The system employs cosine similarity to recommend movies similar to a given title, enhancing user experience through tailored suggestions. The results demonstrate the effectiveness of this method in generating relevant recommendations, contributing to advancements in recommendation algorithms in the entertainment industry.
      - layout: left
        border: weak
        title: Face Mask Detection using CNN
        link: https://github.com/Supratimmannas7/Face-Mask-Detection-using-CNN
        link_text: GitHub Repository
        description: |
          This project focuses on face mask detection using Convolutional Neural Networks (CNNs), utilizing a dataset sourced from Kaggle's open-source repositories. The objective is to develop an automated system capable of accurately identifying individuals wearing face masks in real-time, a critical task in promoting public health and safety. The dataset comprises images categorized into masked and unmasked individuals, which are preprocessed and augmented to improve model robustness. The CNN model is trained to distinguish between the two classes, achieving high accuracy in detection. This project underscores the potential of deep learning techniques in addressing real-world challenges, particularly in monitoring compliance with health guidelines in public spaces.

      - layout: left
        border: weak
        title: Predict Stock Price Movement Using NLP
        link: https://github.com/Supratimmannas7/Predict-Stock-Price-Movement
        link_text: GitHub Repository
        description: |
          This project predicts stock price movement based on news headlines using Natural Language Processing (NLP), utilizing a dataset sourced from Kaggle. By analyzing the sentiment of financial news, we assess its impact on stock market behavior. The data is preprocessed and sentiment scores are calculated, which are then correlated with subsequent stock price movements. My findings demonstrate the effectiveness of NLP techniques in financial forecasting, providing valuable insights for investors.

      - layout: left
        border: weak
        title: Generate CIFAR-10 Small Color Photographs using GAN
        link: https://github.com/Supratimmannas7/Generate-CIFAR10-Small-Color-Photographs-using-GAN
        link_text: GitHub Repository
        description: |
          This project focuses on generating CIFAR-10 small color photographs using Generative Adversarial Networks (GANs). The CIFAR-10 dataset, comprising 60,000 32x32 color images across 10 classes, serves as the training ground for our GAN model. By leveraging the adversarial training process, my aim is to create realistic images that closely resemble the original dataset. The results showcase the GAN's ability to generate diverse and high-quality color photographs, contributing to advancements in image synthesis and demonstrating the potential of GANs in various applications, including data augmentation and creative content generation.
      - layout: left
        border: weak
        title: Image Generation using DDPM
        link: https://github.com/Supratimmannas7/Image-Generation-using-DDPM
        link_text: GitHub Repository
        description: |
          This project focuses on image generation using Denoising Diffusion Probabilistic Models (DDPMs), with the code and dataset sourced from GitHub. By utilizing diffusion processes to iteratively refine noise into coherent images, we aim to capture intricate details and textures across various datasets. The model is trained on a collection of images, allowing it to learn complex distributions and produce visually appealing outputs. My findings demonstrate the effectiveness of DDPM in generating realistic images, showcasing their potential applications in areas such as art, design, and data augmentation.

      - layout: left
        border: weak
        title: Military Aircraft Classification
        link: https://github.com/Supratimmannas7/Military_AirCraft_Classification
        link_text: GitHub Repository
        description: |
          We have implemented a military aircraft classification system using pretrained deep learning models—ResNet50, VGG19, and VGG16—to compare their performance. Conducted extensive evaluations, where ResNet50 outperformed the others, delivering the best classification accuracy. This study highlights the effectiveness of transfer learning in defense applications, ensuring robust and efficient aircraft recognition.
      - layout: left
        border: weak
        title: AI-Agent using Botpress & LLM
        link: https://studio.botpress.cloud/38705770-4002-4c8e-b02e-73e4fd1a3a60/flows/wf-main
        link_text: Botpress Project
        description: |
          I have developed an AI-Agent using DeepSeek prompt engineering to answer user queries based on a predefined Knowledge Base (KB), ensuring data privacy by preventing external data sharing. If the answer is unavailable in the KB, the agent dynamically queries an LLM prompt to generate a response. This approach enables secure model training without exposing sensitive information while optimizing knowledge retrieval efficiency.
          
  - title: Virtual Internship
    layout: list
    content:
      - layout: right
        title: Innovate Intern - AI/ML
        sub_title: AICTE Virtual Internship
        caption: July 2024 - November 2024
        description: |
          Worked on "Deep Learning and NLP" projects, gaining hands-on experience in "Transformer models, GANs, and AI ethics".

  - title: Skills
    layout: text
    content: |
      ## Technical Skills
      - **Programming Languages:** Python, R, SQL
      - **Machine Learning Frameworks:** TensorFlow, PyTorch, Scikit-learn
      - **Deep Learning Techniques:** CNN, RNN, LSTM, GANs, Transformers, Diffusion Models
      - **Mathematical Expertise:** Probability, Linear Algebra, Optimization, Numerical Methods
      - **Data Science Tools:** Pandas, NumPy, Seaborn, Matplotlib

      ## Soft Skills
      - Problem-Solving
      - Analytical Thinking
      - Communication
      - Time Management
      - Team Collaboration


  - title: Certifications
    layout: text
    content: |
      ## Certifications
      - **[Artificial Intelligence Fundamentals](https://www.credly.com/badges/83458eb2-e582-4930-833a-79143d668cd2/public_url)** - IBM
      - **[Python Essentials](https://www.credly.com/badges/f14290dd-3acd-4583-baf8-131af30920f2/public_url)** - Cisco
      - **[Power of Python in Data Analysis](https://drive.google.com/file/d/1sknQc5w1ZsTs0E7FUST6grOHt7s5T8NA/view?usp=sharing)** - Ramkrishna Mission Vidyamandira
      - **[ACMAGRADE Certification](https://drive.google.com/file/d/1bRr21jgOpVMm_n_qAvnDdkp4anmOeJsb/view?usp=sharing)**
      - **[Next2Tech Certification](https://drive.google.com/file/d/11xQqdgsKDbYOY8JqMEANb2vwOhwi6AG9/view?usp=sharing)**


  - title: Achievements
    layout: list
    content:
      - layout: left
        title: GATE-Data Science & AI Qualified
        caption: 2024
      - layout: left
        title: IIT-JAM Mathematics Qualified
        caption: 2023
      - layout: left
        title: IISER Kolkata & IISER TVM M.Sc. Mathematics Entrance Qualified
      - layout: left
        title: Post Matric National Scholarship
        caption: 2020

  - title: Volunteering & Leadership Roles
    layout: list
    content:
      - layout: left
        title: Volunteer, IEEE ICCST 2023
      - layout: left
        title: Volunteer, National Service Scheme (NSS) [2023-2025]
      - layout: left
        title: Student Cultural Coordinator, SPANDAN’24 & SPANDAN’25
      - layout: left
        title: Organizer, PUNECON - IEEE Pune Section International Conference 2024

  - title: Languages & Hobbies
    layout: text
    content: |
      Languages: English, Hindi  
      Hobbies: Badminton, Chess, Cricket  

footer_show_references: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/"]
